version: '3.9'

volumes:
  pgdata:
  redis:


services:
  gateway:
    build:
      context: ./teams/
    restart: always
    ports:
      - 8000:8000
    env_file:
      - docker/env/.env.dev
    depends_on:
      - postgres
      - redis
    networks:
      - olymp_network
    command: bash -c ""
    container_name: gateway_olymp

  users:
    build:
      context: ./users/
    restart: always
    ports:
      - 8001:8000
    env_file:
      - docker/env/.env.dev
    depends_on:
      - postgres
      - redis
    networks:
      - olymp_network
    command: bash -c "alembic upgrade head & python ./users/main.py"
    container_name: users_olymp

  events:
    build:
      context: ./events/
    restart: always
    ports:
      - 8002:8000
    env_file:
      - docker/env/.env.dev
    depends_on:
      - postgres
      - redis
    networks:
      - olymp_network
    command: bash -c "alembic upgrade head & python ./events/main.py"
    container_name: events_olymp

  teams:
    build:
      context: ./teams/
    restart: always
    ports:
      - 8003:8000
    env_file:
      - docker/env/.env.dev
    depends_on:
      - postgres
      - redis
    networks:
      - olymp_network
    command: bash -c "alembic upgrade head & python ./teams/main.py"
    container_name: teams_olymp

  nginx:
    image: nginx:stable-alpine
    restart: always
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/dev/:/etc/nginx/conf.d:ro
    links:
      - gateway
    depends_on:
      - gateway
    container_name: nginx_olymp

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - docker/env/.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data/
    container_name: postgres_olymp

  redis:
    image: redis:alpine
    restart: always
    command:
      - redis-server
    ports:
      - 6379:6379
    env_file:
      - docker/env/.env.dev
    volumes:
      - redis:/data
    container_name: redis_olymp
